export const groups = [
    {
        id: 49,
        date: "03-Feb-26",
        time: "11:05",
        matchup: "Raihan v Samrat Ghosh",
        group: "B1",
    },
    {
        id: 50,
        date: "03-Feb-26",
        time: "11:10",
        matchup: "Shohag Rana v Mehedi Hasan",
        group: "B1",
    },
    {
        id: 51,
        date: "03-Feb-26",
        time: "14:30",
        matchup: "Md. Ariful Islam v MD. JABER AL SALEH",
        group: "A3",
    },
    {
        id: 52,
        date: "03-Feb-26",
        time: "14:40",
        matchup: "Imtiaz Shawn v Mahmudul Hasan Masum",
        group: "B2",
    },
    {
        id: 53,
        date: "03-Feb-26",
        time: "18:05",
        matchup: "Abdul Awal Nadim v Partha",
        group: "A4",
    },
    {
        id: 54,
        date: "03-Feb-26",
        time: "18:10",
        matchup: "Shohel Rana v Raihan",
        group: "B1",
    },
    {
        id: 55,
        date: "03-Feb-26",
        time: "14:40",
        matchup: "Md. Tahseen Rahman vs. Farhan (I)",
        group: "-",
    },
    {
        id: 56,
        date: "03-Feb-26",
        time: "18:20",
        matchup: "Fazle Rabbi vs. Shah Riya Naeem",
        group: "-",
    },
    {
        id: -1,
        date: "04-Feb-26",
        time: "",
        matchup: "Holiday",
        group: "-",
    },
    {
        id: 57,
        date: "05-Feb-26",
        time: "11:05",
        matchup: "Samrat Ghosh vs. Mehedi",
        group: "B1",
    },
    {
        id: 58,
        date: "05-Feb-26",
        time: "11:10",
        matchup: "Shohel Rana vs. Shohag",
        group: "B1",
    },
    {
        id: 59,
        date: "05-Feb-26",
        time: "14:30",
        matchup: "Jaber vs. Fazle Rabbi",
        group: "A3",
    },
    {
        id: 60,
        date: "05-Feb-26",
        time: "14:40",
        matchup: "Nadim vs. Saiful",
        group: "A4",
    },
    {
        id: 61,
        date: "05-Feb-26",
        time: "18:05",
        matchup: "Jaminur vs. Tuhin",
        group: "B2",
    },
    {
        id: 62,
        date: "05-Feb-26",
        time: "18:10",
        matchup: "Ashikur vs. Masum",
        group: "B2",
    },
    {
        id: 63,
        date: "06-Feb-26",
        time: "11:05",
        matchup: "Raihan vs. Mehedi",
        group: "B1",
    },
    {
        id: 64,
        date: "06-Feb-26",
        time: "11:10",
        matchup: "Imtiaz vs. Tuhin",
        group: "B2",
    },
    {
        id: 65,
        date: "06-Feb-26",
        time: "14:20",
        matchup: "Mamun vs. Shagato",
        group: "A1",
    },
    {
        id: 66,
        date: "06-Feb-26",
        time: "14:30",
        matchup: "Larry vs. Aminul",
        group: "A2",
    },
    {
        id: 67,
        date: "06-Feb-26",
        time: "18:05",
        matchup: "Ashikur vs. Jaminur",
        group: "B2",
    },
    {
        id: 68,
        date: "06-Feb-26",
        time: "18:10",
        matchup: "Masum vs. Tuhin",
        group: "B2",
    },
    // Neloy vs. Sagar A1
]